branches:
  - master
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      releaseRules:
        - type: build
          release: patch
        - type: ci
          release: patch
        - type: docs
          release: patch
        - type: fix
          release: patch
        - type: add
          release: minor
        - type: build
          release: minor
        - type: refactor
          release: major
        - type: feat
          release: major
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
